port: 8080
provisioner-port: 8081
distributed-cluster-service-port: 8079
provisioner: "gateway:8081"
hb-port: 9000
control-port: 9001
shell-port: 9002
stdin-port: 9003
iopub-port: 9004
iosub-port: 9005
ack-port: 9006
remote-storage-endpoint: s3
remote-storage: s3
debug: True
direct: false
num-replicas: 3
max-subscribed-ratio: 7.0
local-daemon-service-name: local-daemon-network
global-daemon-service-name: daemon-network
local-daemon-service-port: 8075
ipython-config-path: /home/jovyan/.ipython/profile_default/ipython_config.json
smr-port: 8080
kube-namespace: default
starting-resource-port: 9007
num-resource-ports: 4096
use-stateful-set: false
device-plugin-path: /var/lib/kubelet/device-plugins/
notebook-image-name: scusemua/jupyter-cpu-dev
notebook-image-tag: latest
scheduler-http-port: 8078
scheduling-policy: static
idle-session-reclamation-policy: none
subscribed-ratio-update-interval: 1
num-virtual-gpus-per-node: 72
scaling-factor: 1.05
scaling-interval: 30
scaling-limit: 1.1
scaling-in-limit: 2
predictive_autoscaling: True
scaling-buffer-size: 3
min_cluster_nodes: 4
max_cluster_nodes: 32
gpus-per-host: 8
local_mode: false
deployment_mode: "docker-swarm"
debug_mode: True
debug_port: 9996
using-wsl: false
docker_network_name: traefik-public
execution-time-sampling-window: 10
migration-time-sampling-window: 10
prometheus_interval: 15
prometheus_port: 8089
gpu_poll_interval: 5
num_resend_attempts: 1
acks_enabled: False
simulate_checkpointing_latency: True
remote-docker-event-aggregator-port: 5821
initial-cluster-size: 4
initial-connection-period: 60
election_timeout_seconds: 3
mean_scale_out_per_host_sec: 8
std_dev_scale_out_per_host_sec: 2
mean_scale_in_per_host_sec: 6
std_dev_scale_in_per_host_sec: 1
starting_resource_port: 16007
num_resource_ports: 4096
use_real_gpus: False
assign_kernel_debug_ports: False
submit_execute_requests_one_at_a_time: True
prewarming_enabled: True
initial_num_containers_per_host: 2
min_prewarm_containers_per_host: 2
max_prewarm_containers_per_host: 4
prewarming_policy: maintain_minimum_capacity