version: '3.8'
services:
#  docker-hoster:
#    build:
#      context: ../..
#      dockerfile: deploy/docker/hoster/Dockerfile
#    image: scusemua/docker-hoster:latest
#    labels:
#      app: "distributed_cluster"
#    container_name: 'docker-hoster'
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#      - /etc/hosts:/tmp/hosts
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  jupyter:
    environment:
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/jupyter-debug:latest
    labels:
      app: "distributed_cluster"
    command: start-notebook.sh --NotebookApp.token='' --log-level=DEBUG
    ports:
      - "8888:8888"
    depends_on:
      - gateway
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    environment:
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/gateway:latest
    labels:
      app: "distributed_cluster"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway/gateway.yml:/gateway.yml
    restart: always
    depends_on:
      - prometheus
    ports:
      - "8079:8079"
      - "9996:9996"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  daemon:
    environment:
      - KERNEL_TEMP_BASE=/kernel_base
      - KERNEL_IMAGE=scusemua/jupyter-debug:latest
      - HOST_MOUNT_DIR=/home/$USER/kernel_base
      - TARGET_MOUNT_DIR=/kernel_base
      - STORAGE=/home/$USER/kernel_storage
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/daemon:latest
    labels:
      app: "distributed_cluster"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/$USER/kernel_base:/kernel_base
      - storage:/home/$USER/kernel_storage
      - ./local_daemon/daemon.yml:/daemon.yml
    depends_on:
      - gateway
      - prometheus
    restart: always
    deploy:
      replicas: 4
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
    restart: always

volumes:
  storage:
  coredumps_volume:
  prometheus-data: