- name: Check if git is installed
  command: git --version
  register: git_check
  ignore_errors: true

- name: Install Git if not installed
  apt:
    name: git
    state: present
  when: git_check.rc != 0

- name: Display success message
  debug:
    msg: "Git has been installed successfully."
  when: git_check.rc != 0

- name: Display message if git was already installed
  debug:
    msg: "Git is already installed."
  when: git_check.rc == 0
