- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Create the target directory if it doesn't exist
  file:
    path: "/home/ubuntu/go/pkg"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Clone the GitHub repository
  git:
    repo: "{{gitrepo}}"
    dest: "/home/ubuntu/go/pkg/distributed-notebook"
    version: main  # You can change the branch if necessary
    force: yes
    update: yes
    branch: "{{gitbranch}}"
  become: false  # Clone as the ubuntu user

- name: Ensure correct ownership of the cloned repository
  file:
    path: "/home/ubuntu/go/pkg/distributed-notebook"
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes
