- name: Build the SMR module.
  hosts: vms
  remote_user: "{{ remote_username }}"
  gather_facts: true
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"
  vars:
    python_dir: "{{ python_build_dir }}/Python-{{ python_version }}"
    pip_executable: "/usr/local/bin/pip{{ python_short_version }}"
    ansible_python_interpreter: "{{ python_dir }}/python"

  tasks:
    - name: Build gRPC bindings.
      shell: ". {{ profile_file }} && . {{ python_virtual_env_dir }}/bin/activate && make build-grpc"
      args:
        chdir: "{{ gopath }}/pkg/{{ git_repo_name }}"

    - name: Build in the SMR directory
      shell: ". {{ profile_file }} && . {{ python_virtual_env_dir }}/bin/activate && make build-linux-amd64"
      args:
        chdir: "{{ gopath }}/pkg/{{ git_repo_name }}/smr"

    - name: Build in the root directory
      shell: ". {{ profile_file }} && . {{ python_virtual_env_dir }}/bin/activate && make build-smr-linux-amd64"
      args:
        chdir: "{{ gopath }}/pkg/{{ git_repo_name }}"