- name: Clone the 'distributed-notebook' Git repository from GitHub
  hosts: vms
  remote_user: "{{ remote_username }}"
  become: true       # Run tasks as root
  gather_facts: true
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Create the target directory if it doesn't exist
      file:
        path: "{{ gopath }}/pkg"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clone the GitHub repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ gopath }}/pkg/distributed-notebook"
        force: yes
        update: yes
        clone: true
        version: "{{ gitbranch }}"
      become: false  # Clone as the ubuntu user

    - name: Ensure correct ownership of the cloned repository
      file:
        path: "{{ gopath }}/pkg/distributed-notebook"
        state: directory
        owner: ubuntu
        group: ubuntu
        recurse: yes
