---
- name: Install Protoc (Protocol Buffers Compiler)
  hosts: aws_ec2  # Update with your inventory group
  become: true       # Run tasks as root

  vars:
    protoc_version: "{{protoc_version}}"
    protoc_release_url: "https://github.com/protocolbuffers/protobuf/releases/download/v{{ protoc_version }}/protoc-{{ protoc_version }}-linux-x86_64.zip"
    install_dir: "/home/ubuntu/.local"
    temp_dir: "/tmp"

  tasks:
    - name: Check if protoc is already installed
      command: protoc --version
      register: protoc_installed
      ignore_errors: true

    - name: Download Protoc release if not already installed
      get_url:
        url: "{{ protoc_release_url }}"
        dest: "{{ temp_dir }}/protoc-{{ protoc_version }}-linux-x86_64.zip"
      when: protoc_installed.rc != 0

    - name: Unzip Protoc release into the local directory
      unarchive:
        src: "{{ temp_dir }}/protoc-{{ protoc_version }}-linux-x86_64.zip"
        dest: "{{ install_dir }}"
        remote_src: yes
      when: protoc_installed.rc != 0

    - name: Ensure the local bin directory is in the PATH
      lineinfile:
        path: /home/ubuntu/.bashrc
        regexp: '^export PATH=.*{{ install_dir }}/bin'
        line: 'export PATH="$PATH:{{ install_dir }}/bin"'
        state: present

    - name: Reload .bashrc to apply new PATH
      shell: source /home/ubuntu/.bashrc
      when: protoc_installed.rc != 0

    - name: Verify Protoc installation
      command: protoc --version
      register: protoc_version_output
      when: protoc_installed.rc != 0

    - name: Display Protoc version installed
      debug:
        msg: "Protoc version: {{ protoc_version_output.stdout }}"
      when: protoc_installed.rc != 0
