---

# This playbook is used to create the Docker Swarm cluster.

- name: Create the Docker Swarm cluster
  hosts: docker-swarm
  roles:
    - create-docker-swarm-cluster
  tags:
    - docker
    - swarm
    - start_component
    - install_docker_swarm_cluster