- name: Instruct the Docker Swarm worker nodes to leave the cluster
  hosts: docker_swarm_worker
  roles:
    - leave-docker-swarm

- name: Instruct the Docker Swarm manager nodes to leave the cluster
  hosts: docker_swarm_manager
  roles:
    - leave-docker-swarm