---

- name: Deploy the Distributed Jupyter Notebook cluster on the Docker Swarm cluster
  hosts: docker_swarm
  roles:
    - deploy-distr-notebook-docker-stack
  tags:
    - docker
    - swarm
    - start_component
    - install_distributed_jupyter_notebook_app