---

- name: Deploy the Traefik stack on the Docker Swarm cluster
  hosts: swarm-leader
  roles:
    - deploy-traefik-docker-stack
  tags:
    - docker
    - swarm
    - traefik
    - install_traefik
    - start_component