---
# This playbook first removes the Docker Swarm stack corresponding to the distributed notebook cluster.
# Once removed, the playbook will recreate the stack.

- name: Remove the Distributed Jupyter Notebook stack on the Docker Swarm cluster
  hosts: swarm-leader
  roles:
    - remove-distr-notebook-docker-stack
  tags:
    - docker
    - swarm
    - restart_component
    - reinstall_distributed_jupyter_notebook_app

- name: Remove any remaining kernel replica Docker containers
  hosts: docker_swarm
  roles:
    - remove-kernel-replica-containers
  tags:
    - docker
    - swarm
    - kernel_replica

- name: Prune containers
  hosts: docker_swarm
  roles:
    - prune-docker-containers
  tags:
    - docker
    - swarm

- name: Pull all the latest Docker images for Dashboard Backend, Cluster Gateway, Local Daemon, Jupyter Server, and Kernel Replicas
  hosts: docker_swarm
  roles:
    - pull-docker-images
  tags:
    - docker
    - swarm
    - docker-images

- name: Gather facts on HDFS nodes
  gather_facts: true
  hosts: hadoop_hdfs
    - gather_facts

- name: Gather facts on Swarm nodes
  gather_facts: true
  hosts: docker_swarm
  tags:
    - gather_facts

- name: Redeploy the Distributed Jupyter Notebook cluster on the Docker Swarm cluster
  hosts: docker_swarm
  roles:
    - deploy-distr-notebook-docker-stack
  tags:
    - docker
    - swarm
    - restart_component
    - reinstall_distributed_jupyter_notebook_app