---
# This playbook first removes the Docker Swarm stack corresponding to the distributed notebook cluster.
# Once removed, the playbook will recreate the stack.

- name: Remove the Distributed Jupyter Notebook stack on the Docker Swarm cluster
  hosts: swarm-leader
  roles:
    - remove-swarm-app
  tags:
    - docker
    - swarm
    - restart_component
    - reinstall_distributed_jupyter_notebook_app

- name: Pull all the latest Docker images for Dashboard Backend, Cluster Gateway, Local Daemon, Jupyter Server, and Kernel Replicas
  hosts: docker_swarm
  roles:
    - pull-docker-images
  tags:
    - docker
    - swarm
    - docker-images

- name: Redeploy the Distributed Jupyter Notebook cluster on the Docker Swarm cluster
  hosts: docker_swarm
  roles:
    - create-distr-notebook-docker-stack
  tags:
    - docker
    - swarm
    - restart_component
    - reinstall_distributed_jupyter_notebook_app