apiVersion: v1
kind: Pod
metadata:
  name: core-volume
spec:
  volumes:
  - name: scheduling-path
    hostPath:
      path: /home/scheduling-dump
  containers:
  - name: ubuntu
    image: ubuntu:12.04
    command: ["/bin/sleep","3600"]
    volumeMounts:
    - mountPath: /tmp/cores
      name: scheduling-path
