- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"

- name: Create the target directory if it doesn't exist
  file:
    path: "{{ gopath }}/pkg"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"

- name: Clone the GitHub repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ gopath }}/pkg/{{ git_repo_name }}"
    force: yes
    update: yes
    clone: true
    version: "{{ gitbranch }}"
  become: false  # Clone as the ubuntu user
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"

- name: Ensure correct ownership of the cloned repository
  file:
    path: "{{ gopath }}/pkg/{{ git_repo_name }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"
