apiVersion: v1
kind: Pod
metadata:
  name: annotation-static-scheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: static-scheduler
  containers:
    - name: pod-with-static-scheduler-annotation-container
      image: registry.k8s.io/pause:2.0
