apiVersion: v1
kind: Pod
metadata:
  name: test-pod-vgpu
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: 128Mi
        cpu: "1"
        ds2-lab.github.io/deflated-gpu: "4"
      requests:
        memory: 32Mi
        cpu: "0.2"
        ds2-lab.github.io/deflated-gpu: "4"
  nodeName: distributed-notebook-worker4
