# This playbook is used to remove the Traefik cluster on the Docker Swarm cluster
---

- name: "Remove the {{ traefik_docker_swarm_stack_name }} Docker Swarm stack"
  community.docker.docker_stack:
    name: "{{ traefik_docker_swarm_stack_name }}"
    state: absent
  delegate_to: "{{ groups['docker-swarm-manager'][0] }}"
  become: true
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"