- name: Remove all Docker containers starting with "kernel-" or "prewarm-" in a single command
  command: >
    docker rm -f $(docker ps -q -f "name=^kernel-" -f "name=^prewarm-")
  register: result
  changed_when: result.stdout != ""
  failed_when: result.rc != 0 and "No such container" not in result.stderr