services:

  jupyter:
    # environment:
      # - NOTEBOOK_ARGS="--log-level=DEBUG"
    build: 
      context: ../..
      dockerfile: dockfiles/cpu-python3-amd64/Dockerfile
    image: scusemua/jupyter:latest
    container_name: 'jupyter'
    command: start-notebook.sh --NotebookApp.token='' --log-level=DEBUG
    expose:
      - 8888
    ports:
      - "8888:8888"
    depends_on:
      - gateway
    restart: always

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    image: scusemua/gateway-docker
    container_name: 'gateway'
    restart: always
    ports:
      - "8079:8079"
      - "9996:9996"

  daemon:
    environment:
      - KERNEL_TEMP_BASE=/kernel_base
      - KERNEL_IMAGE=scusemua/jupyter:latest
      - KERNEL_NETWORK=local_daemon_default
      - HOST_MOUNT_DIR=/home/$USER/kernel_base
      - TARGET_MOUNT_DIR=/kernel_base
      - STORAGE=local_daemon_storage
    build:
      context: ./local_daemon
      dockerfile: Dockerfile
    image: scusemua/daemon-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/$USER/kernel_base:/kernel_base
      - storage:/storage
    depends_on:
      - gateway
    restart: always
  
volumes:
  storage: