global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /prometheus
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8000
    dns_sd_configs:
      - names:
          - gateway
          - daemon
        type: A
        port: 8089
    # Docker service discovery
    docker_sd_configs:
      - host: unix:///var/run/docker.sock  # Path to the Docker socket
        filters:
          - name: label
            values: ['app=distributed_cluster', 'component=kernel_replica']