# Hadoop HDFS
hadoop_user: "hadoop"
hadoop_password: "12345"
hadoop_version: "3.3.6"
hadoop_install_dir: /opt/hadoop
java_home: /usr/lib/jvm/java-8-openjdk-amd64
hadoop_config_src: "{{ go_install_parent_dir }}/go/pkg/distributed-notebook/hdfs_configuration/*"
hadoop_env_src: "{{ go_install_parent_dir }}/pkg/distributed-notebook/setup/hadoop-env"