- name: Install ZooKeeper
  hosts: zookeepers
  roles:
    - zookeepers

- name: Install Hadoop HDFS
  hosts: namenode, datanode
  become: true
  roles:
    - install-hadoop-hdfs

- name: Start Hadoop HDFS NameNode
  hosts: namenode
  roles:
    - namenode

- name: Start Hadoop HDFS DataNodes
  hosts: datanode
  roles:
    - datanode