#- hosts: namenode, datanode
#  become: true
#  roles:
#    - common
#
#- hosts: namenode
#  roles:
#    - namenode
#
#- hosts: datanode
#  roles:
#    - datanode

- hosts: zookeepers
  roles:
    - zookeepers