- name: Gather facts about ALL hosts
  hosts: all
  tags:
    info_gathering

- name: Install ZooKeeper
  hosts: zookeepers
  roles:
    - zookeepers
  tags:
    - install_zookeeper
    - hdfs_zookeeper
    - install_component

- name: Install Hadoop HDFS
  hosts: namenode, datanode
  become: true
  roles:
    - install-hadoop-hdfs
  tags:
    - install_hadoop_hdfs
    - hdfs_namenode
    - hdfs_datanode
    - install_component

- name: Start Hadoop HDFS NameNode
  hosts: namenode
  roles:
    - namenode
  tags:
    - start_hdfs_namenode
    - start_component
    - hdfs_namenode

- name: Start Hadoop HDFS DataNodes
  hosts: datanode
  roles:
    - datanode
  tags:
    - start_hdfs_datanodes
    - start_component
    - hdfs_datanode