- name: Delete the JournalNode filesystem directories
  file:
    path: "{{ hdfs_dfs_journalnode_edits_dir }}/{{ hostvars['namenode'].ansible_nodename }}"
    state: absent

- name: Create the JournalNode filesystem directories
  file:
    path: "{{ hdfs_dfs_journalnode_edits_dir }}/{{ hostvars['namenode'].ansible_nodename }}"
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: true

- name: Create the JournalNode systemd service
  template:
    src: hdfs-journalnode.service.j2
    dest: /etc/systemd/system/hdfs-journalnode.service
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
    mode: 0640
  notify:
    - daemon reload
    - journalnode restart
    - journalnode enable
  become: true