# Here, we define the "local-storage" StorageClass and additional resources, including an external provisioner, to manage/provision PVCs of this type.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer