apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-daemon-service-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: default
 name: pod-access-role
rules:
- apiGroups: 
  - "*"
  - ""
  resources: 
  - "events"
  - "pods"
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-daemon-service-account
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-access-role
subjects:
- kind: ServiceAccount
  name: local-daemon-service-account
  namespace: default