- name: reload daemon
  systemd:
    daemon_reload: yes

- name: datanode start
  systemd:
    state: started
    name: hdfs-datanode.service

- name: datanode enable
  systemd:
    name: hdfs-datanode.service
    enabled: yes