version: '2'
services:
  Python:
    image: jupyter/scipy-notebook:python-3.9
    environment:
      GRANT_SUDO: "yes"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: -R
    user: root
    ports:
     - "8888:8888"
    volumes:
     - ../../demo_notebook:/home/jovyan
     - ../..:/home/jovyan/distibuted-notebook
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"