# This playbook is used to deploy the Distributed Jupyter Notebook cluster on the Docker Swarm cluster
---

- name: Ensure the jsondiff Python module is installed
  pip:
    name: jsondiff
    virtualenv: "{{ python_virtual_env_dir }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Pull the latest code changes before installing Docker Swarm app
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ gopath }}/pkg/{{ git_repo_name }}"
    version: "{{ gitbranch }}"
    update: yes
  become: true

- name: "Recursively set owner and group for all files in the local repo to {{ remote_username }}"
  file:
    path: "{{ gopath }}/pkg/{{ git_repo_name }}"
    recurse: yes
    owner: "{{ remote_username }}"
    group: "{{ remote_username }}"
  become: yes

- name: "Deploy the {{ distributed_jupyter_notebook_docker_stack_name }} Docker Swarm stack"
  community.docker.docker_stack:
    name: "{{ distributed_jupyter_notebook_docker_stack_name }}"
    state: present
    compose:
      - "{{ gopath }}/pkg/{{ git_repo_name }}/setup/ansible_unified/roles/deploy-swarm-app/files/docker-compose.yml"
  delegate_to: "{{ groups['docker-swarm-manager'][0] }}"
  become: true
  when: "deploy_distributed_jupyter_notebook_app == true"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"