services:
  jupyter:
    environment:
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/jupyter-cpu:latest
    labels:
      app: "distributed_cluster"
      component: "jupyter_server"
      logging: "promtail"
      logging_jobname: "jupyter"
      traefik.enable: "true"
    command: start-notebook.sh --NotebookApp.token='' --ServerApp.base_url="/jupyter" --log-level=DEBUG
    ports:
      - "8888:8888"
    depends_on:
      - gateway
    deploy:
      placement:
        constraints:
          - "node.labels.swarm_role == swarm-leader"
      restart_policy:
        condition: any
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    environment:
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/gateway:latest
    labels:
      app: "distributed_cluster"
      component: "cluster_gateway"
      logging: "promtail"
      logging_jobname: "gateway"
      traefik.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway/gateway.yml:/gateway.yml
    deploy:
      placement:
        constraints:
          - "node.labels.swarm_role == swarm-leader"
      restart_policy:
        condition: any
    depends_on:
      - prometheus
    ports:
      - "8079:8079"
      - "9996:9996"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  daemon:
    environment:
      - KERNEL_TEMP_BASE_IN_CONTAINER=/kernel_base
      - KERNEL_IMAGE=scusemua/jupyter-cpu:latest
      - HOST_MOUNT_DIR=/home/ubuntu/kernel_base
      - TARGET_MOUNT_DIR=/kernel_base
      - STORAGE=/home/ubuntu/kernel_storage
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
      - USING_WSL2=1
    image: scusemua/daemon:latest
    labels:
      app: "distributed_cluster"
      component: "local_daemon"
      logging: "promtail"
      logging_jobname: "local_daemon"
      traefik.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/kernel_base:/kernel_base
      - ./local_daemon/daemon.yml:/daemon.yml
    depends_on:
      - gateway
      - prometheus
    deploy:
      restart_policy:
        condition: any
      mode: global
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  prometheus:
    ports:
      - "8500:8500"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.listen-address=0.0.0.0:8500
    image: prom/prometheus:main
    deploy:
      restart_policy:
        condition: on-failure
    user: 0:0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:3.2.0
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.2.0
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    labels:
      traefik.enable: "true"
    environment:
      - "GF_SECURITY_ADMIN_USER=grafana"
      - "GF_SECURITY_ADMIN_PASSWORD=12345"
      - "GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,sebastiangunreben-cdf-panel"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter
    labels:
      - "traefik.enable=true"
      - "app=distributed_cluster"
      - "component=node-exporter"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "app=distributed_cluster"
        - "component=node-exporter"
    command:
      - "--web.listen-address=0.0.0.0:{{ node_exporter_port }}"
    networks:
      - traefik-public

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      - "traefik.enable=true"
      - "app=distributed_cluster"
      - "component=cadvisor"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "app=distributed_cluster"
        - "component=cadvisor"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    command:
      - '-port=7126'
      - '-url_base_prefix=/cadvisor'
    networks:
      - traefik-public

  notebook-dashboard:
    image: "scusemua/distributed-notebook-dashboard-backend:latest"
    networks:
      - traefik-public
    environment:
      - "DASHBOARD_CONFIG_DIR=/etc/distributed-notebook-cluster"
    labels: # Container labels
      - "app=distributed_cluster"
      - "component=notebook_dashboard"
      - "logging=promtail"
      - "logging_jobname=notebook_dashboard"
      - "prometheus.metrics.port=8089"
    deploy:
      placement:
        constraints:
          - "node.labels.swarm_role == swarm-leader"
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
      labels:
        - "app=distributed_cluster"
        - "component=notebook_dashboard"
        - "logging=promtail"
        - "logging_jobname=notebook_dashboard"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "prometheus-metrics-provider=true"

        - "traefik.http.routers.notebook-dashboard-http.entryPoints=http"
        - "traefik.http.routers.notebook-dashboard-http.rule=Host(`{{ hostvars['swarm-leader'].ansible_host }}`) && PathPrefix(`/notebook-dashboard`)"
        - "traefik.http.routers.notebook-dashboard-http.service=notebook-dashboard"
        - "traefik.http.services.notebook-dashboard.loadbalancer.server.port={{ dashboard_backend_server_port }}"
    volumes:
      - ./dashboard-backend/config-docker.yaml:/etc/distributed-notebook-cluster/dashboard.yaml
      - ./dashboard-backend/workload-presets-file.yaml:/etc/distributed-notebook-cluster/workload-presets-file.yaml
      - ./dashboard_backend/workload-templates-file.yaml:/etc/distributed-notebook-cluster/workload-templates-file.yaml
      - ./dashboard_backend/workload-job-config.yaml:/etc/distributed-notebook-cluster/workload-job-config.yaml
      - ./dashboard-backend/custom_event_sequences:/etc/distributed-notebook-cluster/custom_event_sequences
      - ./dashboard-backend/.env:/go/.env

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true

volumes:
  coredumps_volume:
  prometheus_data:
  grafana_data:
  loki_data: