package configuration

// CommonOptions includes all configuration parameters that are common to both the Cluster Gateway
// and the Local Daemon components.
type CommonOptions struct {
	DeploymentMode                     string `name:"deployment_mode"                  json:"deployment_mode"                   yaml:"deployment_mode"                     description:"Options are 'docker-compose', 'docker-swarm', and 'kubernetes'."`
	UsingWSL                           bool   `name:"using-wsl"                        json:"using-wsl"                         yaml:"using-wsl"                           description:"Flag indicating whether we're running within WSL2 (Windows Subsystem for Linux). Requires additional networking configuring for the Docker containers."`
	DockerNetworkName                  string `name:"docker_network_name"              json:"docker_network_name"               yaml:"docker_network_name"                 description:"The name of the Docker network that the container is running within. Only used in Docker mode."`
	PrometheusInterval                 int    `name:"prometheus_interval"              json:"prometheus_interval"               yaml:"prometheus_interval"                 description:"Frequency in seconds of how often to publish metrics to Prometheus. So, setting this to 5 means we publish metrics roughly every 5 seconds."`
	PrometheusPort                     int    `name:"prometheus_port"                  json:"prometheus_port"                   yaml:"prometheus_port"                     description:"The port on which this local daemon will serve Prometheus metrics. Default/suggested: 8089."`
	NumResendAttempts                  int    `name:"num_resend_attempts"              json:"num_resend_attempts"               yaml:"num_resend_attempts"                 description:"The number of times to attempt to resend a message before giving up."`
	MessageAcknowledgementsEnabled     bool   `name:"acks_enabled"                     json:"acks_enabled"                      yaml:"acks_enabled"                        description:"MessageAcknowledgementsEnabled indicates whether we send/expect to receive message acknowledgements for the ZMQ messages that we're forwarding back and forth between the various cluster components."`
	SchedulingPolicy                   string `name:"scheduling-policy"                json:"scheduling-policy"                 yaml:"scheduling-policy"                   description:"The scheduling policy to use. Options are 'default, 'static', and 'dynamic'."`
	HdfsNameNodeEndpoint               string `name:"hdfs-namenode-endpoint"           json:"hdfs-namenode-endpoint"            yaml:"hdfs-namenode-endpoint"              description:"Hostname of the HDFS NameNode. The SyncLog's HDFS client will connect to this."`
	SMRPort                            int    `name:"smr-port"                         json:"smr-port"                          yaml:"smr-port"                            description:"Port used by the state machine replication (SMR) protocol."`
	DebugMode                          bool   `name:"debug_mode"                       json:"debug_mode"                        yaml:"debug_mode"                          description:"Enable the debug HTTP server."`
	DebugPort                          int    `name:"debug_port"                       json:"debug_port"                        yaml:"debug_port"                          description:"The port for the debug HTTP server."`
	SimulateCheckpointingLatency       bool   `name:"simulate_checkpointing_latency"   json:"simulate_checkpointing_latency"    yaml:"simulate_checkpointing_latency"      description:"If enabled, then kernels will simulate the latency of performing checkpointing after executing code (write) and after a migration (read)."`
	DisablePrometheusMetricsPublishing bool   `name:"disable_prometheus_metrics_publishing" description:"If passed as true, then the goroutine that publishes Prometheus metrics on an interval will not be created."`
}
