apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: daemon-claim0
  name: daemon-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
status: {}
