apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: storage
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
status: {}
