- name: Delete the Hadoop HDFS NameNode directories
  file:
    path: '{{ hdfs_dfs_namenode_name_dir }}'
    state: absent

- name: Create the Hadoop HDFS NameNode directories
  file:
    path: '{{ hdfs_dfs_namenode_name_dir }}'
    state: directory

- name: Copy the NameNode's SSH keys to the DataNodes
  local_action: "shell ssh root@{{ansible_default_ipv4.address}} 'cat ~/.ssh/id_rsa.pub' | ssh root@{{item}}  'cat >> ~/.ssh/authorized_keys'"
  with_items: "{{groups['datanode']}}"

- name: Wait for the ports be ready for the Hadoop HDFS JournalNodes
  wait_for:
    port: "{{ item }}"
    delay: 10
  with_items:
    - 8485
    - 8480

- name: Format the Hadoop HDFS filesystem
  shell:
    cmd: 'Y | {{hadoop_hdfs_home_dir}}/bin/hdfs namenode -format {{ hdfs_fs_defaultFS }}'
  when: "'namenode' in group_names"
  register: format_filesystem_result
  failed_when: "'FAILED' in format_filesystem_result.stderr"
  async: 500

- debug:
    msg: '{{ format_filesystem_result }}'

- name: Create the Hadoop HDFS NameNode service.
  template:
    src: hdfs-namenode.service.j2
    dest: /etc/systemd/system/hdfs-namenode.service
    mode: 0640
  notify:
    - daemon reload
    - namenode start
  when: "'namenode' in group_names"

- name: Check if the systemd service for the Hadoop HDFS NameNode has started
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  when: "'namenode' in group_names"
  with_items:
    - 'hdfs-namenode.service'

- name: Wait for the ports to be ready after the Hadoop HDFS NameNode has started
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 9000
    delay: 10
  when: "'namenode' in group_names"