kernel-registry-port: 8075
port: 8080
provisioner-port: 8081
provisioner: "gateway:8081"
hb-port: 9000
control-port: 9001
shell-port: 9002
stdin-port: 9003
iopub-port: 9004
iosub-port: 9005
ack-port: 9006
remote-storage-endpoint: bcarver-distributed-notebook-storage
remote-storage: s3
debug: True
direct: false
node_name: 0
num-replicas: 3
max-subscribed-ratio: 7.0
local-daemon-service-name: local-daemon-network
global-daemon-service-name: daemon-network
local-daemon-service-port: 8075
ipython-config-path: /home/jovyan/.ipython/profile_default/ipython_config.json
smr-port: 8080
kube-namespace: default
starting-resource-port: 9007
num-resource-ports: 4096
use-stateful-set: false
device-plugin-path: /var/lib/kubelet/device-plugins/
notebook-image-name: scusemua/jupyter-cpu-dev
notebook-image-tag: latest
scheduler-http-port: 8078
scheduling-policy: static
idle-session-reclamation-policy: none
subscribed-ratio-update-interval: 1
num-virtual-gpus-per-node: 72
scaling-factor: 1.05
scaling-interval: 30
scaling-limit: 1.1
scaling-in-limit: 2
predictive_autoscaling: True
scaling-buffer-size: 3
min_cluster_nodes: 4
max_cluster_nodes: 32
gpus-per-host: 8
local_mode: false
deployment_mode: "docker-swarm"
debug_mode: True
debug_port: 9996
docker-storage-base: "/storage"
using-wsl: false
prometheus_interval: 15
prometheus_port: 8089
num_resend_attempts: 1
acks_enabled: False
simulate_checkpointing_latency: True
run_kernels_in_gdb: False
docker_app_name: distributed_notebook
election_timeout_seconds: 3
mean_scale_out_per_host_sec: 8
std_dev_scale_out_per_host_sec: 2
mean_scale_in_per_host_sec: 6
std_dev_scale_in_per_host_sec: 1
starting_resource_port: 9007
num_resource_ports: 4096
use_real_gpus: False
bind_debugpy_port: False
save_stopped_kernel_containers: False
s3_bucket: bcarver-distributed-notebook-storage
aws_region: us-east-1
redis_password:
redis_port: 6379
redis_database: 0
idle_session_reclamation_enabled: True
idle_session_reclamation_interval_sec: 90
prewarming_enabled: True