- name: daemon reload
  systemd:
    daemon_reload: yes

- name: namenode start
  systemd:
    state: started
    enabled: yes
    name: hdfs-namenode.service

- name: namenode restart
  systemd:
    state: restarted
    name: hdfs-namenode.service