package e2e_testing

const (
	gatewayStaticOptsJson = `
{
  "jaeger_addr": "",
  "consul_addr": "",
  "connection_info": {
    "ip": "",
    "transport": "tcp",
    "signature_scheme": "",
    "key": "",
    "control_port": 9001,
    "shell_port": 9002,
    "stdin_port": 9003,
    "hb_port": 9000,
    "iopub_port": 9004,
    "iosub_port": 9005,
    "ack_port": 9006,
    "num_resource_ports": 4096
  },
  "cluster_daemon_options": {
    "local-daemon-service-name": "local-daemon-network",
    "global-daemon-service-name": "daemon-network",
    "kubernetes-namespace": "",
    "notebook-image-name": "scusemua/jupyter-cpu:latest",
    "notebook-image-tag": "latest",
    "cluster_scheduler_options": {
      "common_options": {
        "deployment_mode": "docker-compose",
        "docker_app_name": "",
        "docker_network_name": "distributed_cluster_default",
        "scheduling-policy": "static",
        "idle-session-reclamation-policy": "none",
        "remote-storage-endpoint": "bcarver2-distributed-notebook-storage",
        "remote-storage": "s3",
        "gpus-per-host": 8,
        "prometheus_interval": 15,
        "prometheus_port": 8089,
        "num_resend_attempts": 1,
        "smr-port": 8080,
        "debug_port": 9996,
        "election_timeout_seconds": 3,
        "local_mode": true,
        "use_real_gpus": false,
        "acks_enabled": false,
        "debug_mode": true,
        "simulate_checkpointing_latency": true,
        "disable_prometheus_metrics_publishing": false,
        "simulate_training_using_sleep": false,
        "bind_debugpy_port": false,
        "save_stopped_kernel_containers": false,
        "retrieve_datasets_from_s3": false,
        "datasets_s3_bucket": "",
        "pretty_print_options": true
      },
      "custom_idle_session_reclamation_options": {
        "idle_session_replay_all_cells": false,
        "idle_session_timeout_interval_sec": 0
      },
      "subscribed-ratio-update-interval": 0,
      "scaling-factor": 1.1,
      "scaling-interval": 15,
      "scaling-limit": 1.15,
      "scaling-in-limit": 2,
      "scaling-buffer-size": 3,
      "min_cluster_nodes": 6,
      "max_cluster_nodes": 48,
      "initial-cluster-size": 12,
      "gpu_poll_interval": 5,
      "max-subscribed-ratio": 7,
      "execution-time-sampling-window": 10,
      "migration-time-sampling-window": 10,
      "scheduler-http-port": 8078,
      "mean_scale_out_per_host_sec": 15,
      "std_dev_scale_out_per_host_sec": 2,
      "mean_scale_in_per_host_sec": 10,
      "std_dev_scale_in_per_host_sec": 1,
      "millicpus_per_host": 0,
      "memory_mb_per_host": 0,
      "vram_gb_per_host": 0,
      "prewarming_enabled": false,
      "min_prewarm_containers_per_host": 2,
      "max_prewarm_containers_per_host": 4,
      "initial_num_containers_per_host": 2,
      "prewarm_run_interval_sec": 0,
      "littles_law_prewarmer_w": 25,
      "littles_law_prewarmer_lambda": 0.2,
      "prewarming_policy": "maintain_minimum_capacity",
      "initial-connection-period": 20,
      "predictive_autoscaling": false,
      "assign_kernel_debug_ports": false
    },
    "local-daemon-service-port": 8075,
    "global-daemon-service-port": 0,
    "distributed-cluster-service-port": 8079,
    "remote-docker-event-aggregator-port": 5821,
    "idle_session_reclamation_interval_sec": 90,
    "submit_execute_requests_one_at_a_time": true,
    "use-stateful-set": false,
    "idle_session_reclamation_enabled": true
  },
  "port": 10000,
  "provisioner_port": 10001
}
`
	localSchedulerStaticOptsJson = `
{
  "aws_region": "us-east-1",
  "connection_info": {
    "ip": "",
    "transport": "tcp",
    "signature_scheme": "",
    "key": "",
    "control_port": 19001,
    "shell_port": 19002,
    "stdin_port": 19003,
    "hb_port": 19000,
    "iopub_port": 19004,
    "iosub_port": 19005,
    "ack_port": 19006,
    "starting_resource_port": 29007,
    "num_resource_ports": 4096
  },
  "consul": "",
  "jaeger": "",
  "kernel-registry-port": 18075,
  "node_name": "0",
  "port": 18082,
  "provisioner": "127.0.0.1:10000",
  "redis_database": 0,
  "redis_password": "",
  "redis_port": 6379,
  "s3_bucket": "distributed-notebook-storage",
  "scheduler_daemon_options": {
    "docker-storage-base": "/remote_storage",
    "direct": false,
    "run_kernels_in_gdb": false,
    "cluster_scheduler_options": {
      "common_options": {
        "deployment_mode": "docker-compose",
        "docker_app_name": "distributed_notebook",
        "docker_network_name": "",
        "scheduling-policy": "static",
        "idle-session-reclamation-policy": "none",
        "remote-storage-endpoint": "redis:6379",
        "remote-storage": "redis",
        "gpus-per-host": 8,
        "prometheus_interval": 15,
        "prometheus_port": -1,
        "num_resend_attempts": 1,
        "smr-port": 17080,
        "debug_port": 19997,
        "election_timeout_seconds": 3,
        "local_mode": true,
        "use_real_gpus": false,
        "acks_enabled": false,
        "debug_mode": true,
        "simulate_checkpointing_latency": true,
        "disable_prometheus_metrics_publishing": false,
        "simulate_training_using_sleep": false,
        "bind_debugpy_port": false,
        "save_stopped_kernel_containers": false,
        "pretty_print_options": false
      },
      "custom_idle_session_reclamation_options": {
        "idle_session_replay_all_cells": false,
        "idle_session_timeout_interval_sec": 0
      },
      "subscribed-ratio-update-interval": 1,
      "scaling-factor": 1.1,
      "scaling-interval": 15,
      "scaling-limit": 1.15,
      "scaling-in-limit": 2,
      "scaling-buffer-size": 3,
      "min_cluster_nodes": 6,
      "max_cluster_nodes": 48,
      "gpu_poll_interval": 0,
      "max-subscribed-ratio": 7,
      "execution-time-sampling-window": 0,
      "migration-time-sampling-window": 0,
      "scheduler-http-port": 8078,
      "mean_scale_out_per_host_sec": 0,
      "std_dev_scale_out_per_host_sec": 0,
      "mean_scale_in_per_host_sec": 0,
      "std_dev_scale_in_per_host_sec": 0,
      "millicpus_per_host": 64000,
      "memory_mb_per_host": 128000,
      "vram_gb_per_host": 40,
      "predictive_autoscaling": true,
      "assign_kernel_debug_ports": false
    }
  },
  "virtual_gpu_plugin_server_options": {
    "device-plugin-path": "/var/lib/kubelet/device-plugins/",
    "num-virtual-gpus-per-node": 72
  }
}
`
)
