- name: daemon reload
  systemd:
    daemon_reload: yes

- name: journalnode restart
  systemd:
    state: restarted
    name: hdfs-journalnode.service

- name: journalnode enable
  systemd:
    name: hdfs-journalnode.service
    enabled: yes