---
- name: Pull the latest code changes, discarding any local changes.
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ gitbranch }}"
    update: yes
    force: true
  become: true

- name: Recursively change ownership of the go directory
  ansible.builtin.file:
    path: "{{ go_install_parent_dir }}/go/{{ git_repo_name }}"
    recurse: yes
    owner: "{{ remote_username }}"
    group: "{{ remote_username }}"