apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: jupyter-notebook
  name: JupyterNotebook
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: jupyter-notebook
status:
  loadBalancer: {}
