apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - args:
            - start-notebook.sh
            - --NotebookApp.token=
            - --log-level=DEBUG
          image: scusemua/jupyter:latest
          name: jupyter-notebook
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}
