services:
  # consul:
  #   image: consul:latest
  #   ports:
  #     - "8300:8300"
  #     - "8400:8400"
  #     - "8500:8500"
  #     - "8600:53/udp"
  #   restart: always

  jupyter:
    environment:
      - NOTEBOOK_ARGS="--log-level=DEBUG"
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
    build: 
      context: ../..
      dockerfile: dockfiles/cpu-python3-arm64/Dockerfile
    image: scusemua/jupyter:latest
    deploy:
      labels:
        app: "distributed_cluster"
    container_name: 'jupyter'
    command: start-notebook.sh --NotebookApp.token='' --log-level='DEBUG'
    ports:
      - "8888:8888"
    depends_on:
      - gateway
    restart: always

  gateway:
    environment:
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
    build: 
      context: ../gateway
      dockerfile: Dockerfile
    image: scusemua/gateway
    deploy:
      labels:
        app: "distributed_cluster"
    container_name: 'gateway'
    restart: always

  daemon:
    environment:
      - KERNEL_TEMP_BASE_IN_CONTAINER=/kernel_base
      - KERNEL_IMAGE=scusemua/jupyter:latest
      - KERNEL_NETWORK=local_daemon_default
      - HOST_MOUNT_DIR=/home/$USER/kernel_base
      - TARGET_MOUNT_DIR=/kernel_base
      - STORAGE=local_daemon_storage
      - DOCKER_NETWORK_NAME=distributed_cluster_default # If you change the name of the docker compose app, then you must change this as well.
    build:
      context: ../..
      dockerfile: dockfiles/local-daemon/Dockerfile
    image: scusemua/daemon
    deploy:
      labels:
        app: "distributed_cluster" # Note: if you change this, you must update the `DOCKER_NETWORK_NAME` environment variable passed to the local daemons, defined above.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/$USER/kernel_base:/kernel_base
      - storage:/storage
    depends_on:
      - gateway
    restart: always

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: 'gateway_jaeger'
  #   ports:
  #     - "14269"
  #     - "5778:5778"
  #     - "14268:14268"
  #     - "14267"
  #     - "16686:16686"
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #   restart: always

volumes:
  storage: