---
- name: Pull the dashboard backend Docker image
  community.docker.docker_image_pull:
    name: "{{ dashboard_backend_docker_username }}/{{ dashboard_backend_docker_image_name }}"
    pull: always
    tag: "{{ dashboard_backend_docker_image_tag }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Pull the Gateway Docker image
  community.docker.docker_image_pull:
    name: "{{ gateway_docker_username }}/{{ gateway_docker_image_name }}"
    pull: always
    tag: "{{ gateway_docker_image_tag }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Pull the Local Daemon Docker image
  community.docker.docker_image_pull:
    name: "{{ local_daemon_docker_username }}/{{ local_daemon_docker_image_name }}"
    pull: always
    tag: "{{ local_daemon_docker_image_tag }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Pull the Jupyter Server Docker image
  community.docker.docker_image_pull:
    name: "{{ jupyter_server_docker_username }}/{{ jupyter_server_docker_image_name }}"
    pull: always
    tag: "{{ jupyter_server_docker_image_tag }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Pull the kernel Docker image
  community.docker.docker_image_pull:
    name: "{{ jupyter_server_docker_username }}/{{ jupyter_server_docker_image_name }}"
    pull: always
    tag: "{{ jupyter_server_docker_image_tag }}"
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"