# This playbook is used to remove the Distributed Jupyter Notebook cluster on the Docker Swarm cluster
---

- name: "Remove the {{ distributed_notebook_docker_stack_name }} Docker Swarm stack"
  community.docker.docker_stack:
    name: "{{ distributed_notebook_docker_stack_name }}"
    state: absent
  when: "inventory_hostname in 'swarm-leader'"
  become: true
  environment:
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ python_build_dir }}/Python-{{ python_version }}"
  vars:
    ansible_python_interpreter: "{{ python_virtual_env_dir }}/bin/python3.12"

- name: Reset the permissions on /var/run/docker.sock so that we can mount it to the Local Daemon containers
  shell: chmod -R 660 /var/run/docker.sock
  become: true