	var err error
	var ok bool
	var insufficientResourcesError *scheduling.InsufficientResourcesError

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6500,61000,5,27))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1500,3000,3,5))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(1))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6500,61000,5,27))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1500,3000,3,5))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6000,60000,2,20))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2000,4000,6,12))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel2")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6000,60000,2,20))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2000,4000,6,12))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(5500,59000,1,19))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2500,5000,7,13))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(1))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel3Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(5500,59000,1,19))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2500,5000,7,13))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6000,60000,2,20))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2000,4000,6,12))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.ReleaseCommittedResources(1, "Kernel2")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(3000,52000,6,29))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5000,12000,2,3))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(1))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(1))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel3")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(2))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.CPU)).To(BeTrue())
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).ToNot(BeNil())
	ok = errors.As(err, &insufficientResourcesError)
	Expect(ok).To(BeTrue())
	Expect(insufficientResourcesError).ToNot(BeNil())
	Expect(len(insufficientResourcesError.OffendingResourceKinds)).To(Equal(1))
	Expect(containsOffendingResourceKind(insufficientResourcesError.OffendingResourceKinds, scheduling.GPU)).To(BeTrue())
	Expect(kernel2Spec.Equals(insufficientResourcesError.RequestedResources)).To(BeTrue())
	Expect(resourceManager.IdleResources().Equals(insufficientResourcesError.AvailableResources)).To(BeTrue())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(3))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(1))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(1500,49000,3,24))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6500,15000,5,8))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))

	err = resourceManager.ReleaseCommittedResources(1, "Kernel3")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2000,50000,4,25))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6000,14000,4,7))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel3")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2000,50000,4,25))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6000,14000,4,7))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(3000,52000,6,29))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5000,12000,2,3))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.ReleaseCommittedResources(1, "Kernel3")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6000,60000,2,20))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2000,4000,6,12))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel2")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(6000,60000,2,20))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2000,4000,6,12))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel2")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7000,62000,6,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(1000,2000,2,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(8000,64000,8,32))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(0,0,0,0))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(0))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(4))

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())

	err = resourceManager.CommitResources(1, "Kernel3", kernel3Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel4")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(3000,52000,6,29))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5000,12000,2,3))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.CommitResources(1, "Kernel1", kernel1Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2000,50000,4,25))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(6000,14000,4,7))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel1")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(3000,52000,6,29))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5000,12000,2,3))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.CommitResources(1, "Kernel4", kernel4Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(2500,51000,5,28))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(5500,13000,3,4))).To(BeTrue())

	err = resourceManager.ReleaseCommittedResources(1, "Kernel3")
	Expect(err).To(BeNil())
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(7500,63000,7,31))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(500,1000,1,1))).To(BeTrue())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(1))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(3))

	err = resourceManager.CommitResources(1, "Kernel2", kernel2Spec, false)
	Expect(err).To(BeNil())
	GinkgoWriter.Printf("resourceManager.CommittedResources(): %s\n", resourceManager.CommittedResources().String())
	Expect(resourceManager.NumAllocations()).To(Equal(4))
	Expect(resourceManager.NumCommittedAllocations()).To(Equal(2))
	Expect(resourceManager.NumPendingAllocations()).To(Equal(2))
	Expect(resourceManager.IdleResources().Equals(types.NewDecimalSpec(5500,59000,1,19))).To(BeTrue())
	Expect(resourceManager.CommittedResources().Equals(types.NewDecimalSpec(2500,5000,7,13))).To(BeTrue())
