kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: default
 name: cluster-gateway-role
rules:
- apiGroups: 
  - "*"
  - ""
  resources: 
  - "events"
  - "pods"
  - "namespaces"
  - "configmaps"
  - "clonesets"
  - "services"
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete" 