apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-configmap 
  namespace: default 
data:
  # device-plugin-port: {{ .Values.local_daemon.device_plugin.port }}
  daemon.yml: | 
    kernel-registry-port: {{ .Values.local_daemon.network.jupyter.kernel_registry_port }} 
    port: {{ .Values.local_daemon.network.port }}
    provisioner-port: {{ .Values.gateway.provisioner_port }}
    provisioner: "gateway:{{ .Values.gateway.provisioner_port }}"
    hb-port: {{ .Values.local_daemon.network.jupyter.hb_port }}
    control-port: {{ .Values.local_daemon.network.jupyter.control_port }}
    shell-port: {{ .Values.local_daemon.network.jupyter.shell_port }}
    stdin-port: {{ .Values.local_daemon.network.jupyter.stdin_port }}
    iopub-port: {{ .Values.local_daemon.network.jupyter.iopub_port1 }}
    iosub-port: {{ .Values.local_daemon.network.jupyter.iopub_port2 }}
    hdfs-namenode-endpoint: {{ .Values.hdfs.namenode_endpoint }}
    debug: {{ .Values.common.debug }}
    direct: false
    num-replicas: 3
    max-subscribed-ratio: 7.0
    local-daemon-service-name: {{ .Values.local_daemon.network.local_service_name }}
    global-daemon-service-name: {{ .Values.local_daemon.network.global_service_name }}
    local-daemon-service-port: {{ .Values.local_daemon.network.service_port }}
    ipython-config-path: {{ .Values.common.ipython_config_path }}
    smr-port: {{ .Values.smr.port }}
    kube-namespace: {{ .Values.namespace }}
    starting-resource-port: {{ .Values.local_daemon.network.jupyter.starting_resource_port }}
    num-resource-ports: {{ mul (div .Values.local_daemon.max_actual_gpu_per_node .Values.local_daemon.gpu_allocation_granularity) 2 }}
    use-stateful-set: {{ .Values.common.use_stateful_set }}
    device-plugin-path: {{ .Values.local_daemon.device_plugin.path }}
    num-virtual-gpus-per-node: {{ .Values.local_daemon.num_virtual_gpus_per_node }}