apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
        app: gateway
    spec:
      containers:
        - image: {{ .Values.gateway.image }}:{{ .Values.gateway.image_tag }}
          name: gateway
          command: ["./gateway"]
          args: ["-yaml", "{{ .Values.common.config_file_dir }}/daemon.yml", "-debug"]
          resources: {}
          ports:
          - name: tcp
            containerPort: {{ .Values.local_daemon.network.service_port }}
          - name: hb-port
            containerPort: {{ .Values.local_daemon.network.jupyter.hb_port }}
          - name: control-port
            containerPort: {{ .Values.local_daemon.network.jupyter.control_port }}
          - name: shell-port
            containerPort: {{ .Values.local_daemon.network.jupyter.shell_port }}
          - name: stdin-port
            containerPort: {{ .Values.local_daemon.network.jupyter.stdin_port }}
          - name: iopub-port1
            containerPort: {{ .Values.local_daemon.network.jupyter.iopub_port1 }}
          - name: iopub-port2
            containerPort: {{ .Values.local_daemon.network.jupyter.iopub_port2 }}
          - name: jupyter
            containerPort: {{ .Values.gateway.grpc_port }}
          - name: provisioner
            containerPort: {{ .Values.gateway.provisioner_port }}
          {{- $portsRequired := mul (div .Values.local_daemon.max_gpu_per_node .Values.local_daemon.gpu_allocation_granularity) 2 | int -}}
          {{- $nextPort := .Values.local_daemon.network.jupyter.starting_resource_port | int -}}
          {{- range $i := until $portsRequired }}
          - name: {{ printf "resource-port-%d" $i }}
            port: {{ $nextPort | int }}
            {{- $nextPort = add $nextPort 1 | int}}
          {{- end }}
          volumeMounts:
            - name: gateway-config-file
              mountPath: "{{ .Values.common.config_file_dir }}/daemon.yml"
              subPath: daemon.yml
          env:
            - name: SHARED_CONFIG_DIR
              value: "{{ .Values.common.config_file_dir }}"
            - name: IPYTHON_CONFIG_PATH
              value: {{ .Values.common.ipython_config_path }}
      restartPolicy: Always
      serviceAccountName: gateway-service-account
      volumes:
        - name: gateway-config-file
          configMap:
            name: daemon-configmap 
            defaultMode: 384
status: {}
