apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: jupyter
      port: {{ .Values.gateway.grpc_port }}
      targetPort: {{ .Values.gateway.grpc_port }}
    - name: provisioner
      port: {{ .Values.gateway.provisioner_port }}
      targetPort: {{ .Values.gateway.provisioner_port }}
    - name: tcp
      port: {{ .Values.local_daemon.network.service_port }}
      protocol: TCP
    - name: hb-port
      port: {{ .Values.local_daemon.network.jupyter.hb_port }}
    - name: control-port
      port: {{ .Values.local_daemon.network.jupyter.control_port }}
    - name: shell-port
      port: {{ .Values.local_daemon.network.jupyter.shell_port }}
    - name: stdin-port
      port: {{ .Values.local_daemon.network.jupyter.stdin_port }}
    - name: iopub-port1
      port: {{ .Values.local_daemon.network.jupyter.iopub_port1 }}
    - name: iopub-port2
      port: {{ .Values.local_daemon.network.jupyter.iopub_port2 }}
    {{- $portsRequired := mul (div .Values.local_daemon.max_gpu_per_node .Values.local_daemon.gpu_allocation_granularity) 2 | int -}}
    {{- $nextPort := .Values.local_daemon.network.jupyter.starting_resource_port | int -}}
    {{- range $i := until $portsRequired }}
    - name: {{ printf "resource-port-%d" $i }}
      port: {{ $nextPort | int }}
      {{- $nextPort = add $nextPort 1 | int}}
    {{- end }}
  selector:
    app: gateway 
    io.kompose.service: gateway
  type: LoadBalancer
status:
  loadBalancer: {}
