apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "{{ .Values.gateway.port }}"
      port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
