apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
        app: gateway
    spec:
      env:
        - name: SHARED_CONFIG_DIR
          value: "{{ .Values.common.node_local_pvc_mount_point }}/{{ .Values.common.config_file_dir }}"
        - name: IPYTHON_CONFIG_PATH
          value: {{ .Values.common.ipython_config_path }}
      containers:
        - image: {{ .Values.gateway.image }}:{{ .Values.gateway.image_tag }}
          name: gateway
          resources: {}
      restartPolicy: Always
      serviceAccountName: gateway-service-account
status: {}
