# Here, we define the "local-storage" StorageClass and additional resources, including an external provisioner, to manage/provision PVCs of this type.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config 
  namespace: default 
data:
  storageClassMap: |     
    {{- range $classConfig := .Values.classes }}
    {{ $classConfig.name }}:
      hostDir: {{ $classConfig.hostDir }}
      mountDir: {{ $classConfig.mountDir | default $classConfig.hostDir }}
      {{- if $classConfig.blockCleanerCommand }}
      blockCleanerCommand:
      {{- range $val := $classConfig.blockCleanerCommand }}
        - {{ $val | quote }}
      {{- end}}
      {{- end }}
      {{- if $classConfig.volumeMode }}
      volumeMode: {{ $classConfig.volumeMode }}
      {{- end }}
      {{- if $classConfig.fsType }}
      fsType: {{ $classConfig.fsType }}
      {{- end }}
      {{- if $classConfig.namePattern }}
      namePattern: {{ $classConfig.namePattern | quote }}
      {{- end }}
    {{- end }}