apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jupyter-notebook
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: jupyter-notebook
    spec:
      containers:
        - args:
            - start-notebook.sh
            - --NotebookApp.token=
            - --log-level=DEBUG
          image: {{ .Values.notebook_server.image }}:{{ .Values.notebook_server.image_tag}}
          name: jupyter-notebook
          ports:
            - containerPort: {{ .Values.notebook_server.port }}
          resources: {}
          ports:
          - name: tcp
            containerPort: {{ .Values.local_daemon.network.service_port }}
          - name: hb-port
            containerPort: {{ .Values.local_daemon.network.jupyter.hb_port }}
          - name: control-port
            containerPort: {{ .Values.local_daemon.network.jupyter.control_port }}
          - name: shell-port
            containerPort: {{ .Values.local_daemon.network.jupyter.shell_port }}
          - name: stdin-port
            containerPort: {{ .Values.local_daemon.network.jupyter.stdin_port }}
          - name: iopub-port1
            containerPort: {{ .Values.local_daemon.network.jupyter.iopub_port1 }}
          - name: iopub-port2
            containerPort: {{ .Values.local_daemon.network.jupyter.iopub_port2 }}
          - name: jupyter
            containerPort: {{ .Values.gateway.grpc_port }}
          - name: provisioner
            containerPort: {{ .Values.gateway.provisioner_port }}
      restartPolicy: Always
status: {}