kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: default
 name: pod-access-role
rules:
- apiGroups: 
  - ""
  resources: 
  - "events"
  - "pods"
  - "Pods"
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete" 