apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler_extender.config_map_name }}
  namespace: default
data:
  {{ .Values.scheduler_extender.config_file_name }}: |
    port: 80
    cluster-gateway-port: {{ .Values.gateway.scheduler.scheduler_http_port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler-config
  namespace: default
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: static-scheduler
        percentageOfNodesToScore: 100 
      - schedulerName: dynamic-v3-scheduler
        percentageOfNodesToScore: 100 
      - schedulerName: dynamic-v4-scheduler
        percentageOfNodesToScore: 25 
    extenders:
      - urlPrefix: "http://localhost/"
        filterVerb: "filter"
        prioritizeVerb: ""
        preemptVerb: ""
        bindVerb: ""
        weight: 1
        enableHTTPS: false
        nodeCacheCapable: false
        tlsConfig:
          insecure: true
    leaderElection:
      leaderElect: true
      resourceName: scheduler-extender
      resourceNamespace: default