apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-extender
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-extender-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: scheduler-extender
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler_extender.config_map_name }}
  namespace: kube-system
data:
  {{ .Values.scheduler_extender.config_file_name }}: |
    port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: static-scheduler
        percentageOfNodesToScore: 100 
      - schedulerName: dynamic-v3-scheduler
        percentageOfNodesToScore: 100 
      - schedulerName: dynamic-v4-scheduler
        percentageOfNodesToScore: 25 
    extenders:
      - urlPrefix: "http://localhost/"
        filterVerb: "filter"
        prioritizeVerb: ""
        preemptVerb: ""
        bindVerb: ""
        weight: 1
        enableHTTPS: false
        nodeCacheCapable: false
        tlsConfig:
          insecure: true
    leaderElection:
      leaderElect: true
      resourceName: scheduler-extender
      resourceNamespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
  namespace: kube-system
  labels:
    app: scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
  template:
    metadata:
      labels:
        app: scheduler-extender
    spec:
      serviceAccountName: scheduler-extender
      volumes:
        - name: kube-scheduler-config
          configMap:
            name: kube-scheduler-config
        - name: scheduler-extender-configuration
          configMap:
            name: {{ .Values.scheduler_extender.config_map_name }}
      containers:
        - name: scheduler-ctr
          image: registry.k8s.io/kube-scheduler:v1.29.2
          imagePullPolicy: IfNotPresent
          args:
          - kube-scheduler
          - --config=/scheduler-extender/config.yaml
          - --bind-address=0.0.0.0
          - --feature-gates=StatefulSetStartOrdinal=true
          - --leader-elect=true
          - -v=8
          volumeMounts:
            - name: kube-scheduler-config
              mountPath: /scheduler-extender
        - name: scheduler-extender-ctr
          image: {{ .Values.scheduler_extender.image }}:{{ .Values.scheduler_extender.image_tag }}
          imagePullPolicy: Always
          command: ["./scheduler_extender"]
          args: ["-yaml", "scheduler-extender-configuration/{{ .Values.scheduler_extender.config_file_name }}", "-debug"]
          volumeMounts:
            - name: "scheduler-extender-configuration"
              mountPath: "scheduler-extender-configuration/{{ .Values.scheduler_extender.config_file_name }}"
              subPath: "{{ .Values.scheduler_extender.config_file_name }}"
          livenessProbe:
            httpGet:
              path: /version
              port: 80
          readinessProbe:
            httpGet:
              path: /version
              port: 80
          ports:
            - containerPort: 80