- name: Install the Python module from pyproject.toml
  shell: ". {{ profile_file}} && {{ python_virtual_env_dir }}/bin/pip3 install -e ."
  args:
    chdir: "{{ gopath }}/pkg/{{ git_repo_name }}"
  register: install_result
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"
  vars:
    python_dir: "{{ python_build_dir }}/Python-{{ python_version }}"
    pip_executable: "/usr/local/bin/pip{{ python_short_version }}"
    ansible_python_interpreter: "{{ python_dir }}/python"

- name: Fail if installation failed
  fail:
    msg: "Installation failed: {{ install_result.stderr }}"
  when: install_result.rc != 0
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"
  vars:
    python_dir: "{{ python_build_dir }}/Python-{{ python_version }}"
    pip_executable: "/usr/local/bin/pip{{ python_short_version }}"
    ansible_python_interpreter: "{{ python_dir }}/python"

- name: Display success message if installation was successful
  debug:
    msg: "Python module installed successfully from {{ gopath }}/pkg/{{ git_repo_name }}"
  when: install_result.rc == 0
  environment:
    LD_LIBRARY_PATH: "{{ python_build_dir }}/Python-{{ python_version }}:$LD_LIBRARY_PATH"
  vars:
    python_dir: "{{ python_build_dir }}/Python-{{ python_version }}"
    pip_executable: "/usr/local/bin/pip{{ python_short_version }}"
    ansible_python_interpreter: "{{ python_dir }}/python"
