- name: Create the daemon.json Docker configuration file
  template:
    src: docker-daemon.json.j2
    dest: "{{ docker_config_file_path }}"
    mode: 0777
    owner: "{{ remote_username }}"
    group: "{{ remote_username }}"
  become: true