local-daemon-service-port: 8075
scheduler-http-port: 8078
distributed-cluster-service-port: 8079
port: 8080
smr-port: 8080
provisioner-port: 8081
prometheus_port: 8089
hb-port: 9000
control-port: 9001
shell-port: 9002
stdin-port: 9003
iopub-port: 9004
iosub-port: 9005
ack-port: 9006
starting-resource-port: 9007
debug_port: 9996
num-resource-ports: 4096
provisioner: "gateway:8081"
#remote-storage-endpoint: host.docker.internal:10000
#remote-storage: hdfs
remote-storage: redis
remote-storage-endpoint: redis:6379
debug: true
direct: false
num-replicas: 3
max-subscribed-ratio: 7.0
local-daemon-service-name: local-daemon-network
global-daemon-service-name: daemon-network
ipython-config-path: /home/jovyan/.ipython/profile_default/ipython_config.json
kube-namespace: default
use-stateful-set: false
device-plugin-path: /var/lib/kubelet/device-plugins/
notebook-image-name: scusemua/jupyter-cpu-dev:latest
notebook-image-tag: latest
idle-session-reclamation-policy: none
scheduling-policy: middle-ground
num-virtual-gpus-per-node: 72
scaling-factor: 1.10
scaling-interval: 15
scaling-limit: 1.15
scaling-in-limit: 2
predictive_autoscaling: false
scaling-buffer-size: 3
min_cluster_nodes: 6
max_cluster_nodes: 48
gpus-per-host: 8
local_mode: false
deployment_mode: "docker-compose"
debug_mode: true
using-wsl: true 
docker_network_name: distributed_cluster_default
execution-time-sampling-window: 10
migration-time-sampling-window: 10
prometheus_interval: 15
gpu_poll_interval: 5
num_resend_attempts: 1
acks_enabled: false
checkpointing_enabled: true
remote-docker-event-aggregator-port: 5821
initial-cluster-size: 3
initial-connection-period: 20
election_timeout_seconds: 4
simulate_checkpointing_latency: true
mean_scale_out_per_host_sec: 4
std_dev_scale_out_per_host_sec: 1
mean_scale_in_per_host_sec: 2
std_dev_scale_in_per_host_sec: 0.75
starting_resource_port: 9007
num_resource_ports: 4096
use_real_gpus: false
assign_kernel_debug_ports: false
submit_execute_requests_one_at_a_time: true
idle_session_reclamation_enabled: false
idle_session_reclamation_interval_sec: 60
pretty_print_options: true
prewarming_enabled: true
initial_num_containers_per_host: 2
min_prewarm_containers_per_host: 2
max_prewarm_containers_per_host: -1
littles_law_prewarmer_w: 25
littles_law_prewarmer_lambda: 0.20
replenish_on_use: false
dynamically_maintain_capacity: false
prewarming_policy: maintain_minimum_capacity
# prewarming_policy: no_maintenance
# prewarming_policy: little_law_capacity