apiVersion: v1
kind: Pod
metadata:
  name: test-pod-node2
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: 128Mi
        cpu: "1"
      requests:
        memory: 32Mi
        cpu: "0.2"
  nodeName: distributed-notebook-worker2
