# This Playbook deploys the entire distributed-notebook cluster.

- name: Install distributed-notebook Dependencies on All Nodes
  hosts: vms
  tags:
    - install_component
    - distributed_notebook
  roles:
    - distributed-notebook-cluster

- name: Gather facts about the HDFS NameNodes
  hosts: namenode
  tags:
    - info_gathering
    - hdfs_namenode

- name: Gather facts about the HDFS DataNodes
  hosts: datanode
  tags:
    - info_gathering
    - hdfs_datanode

- name: Gather facts about the ZooKeeper nodes
  hosts: zookeepers
  tags:
    - info_gathering
    - hdfs_zookeeper

- name: Install ZooKeeper
  hosts: zookeepers
  roles:
    - zookeepers
  tags:
    - install_zookeeper
    - hdfs_zookeeper
    - install_component

- name: Install Hadoop HDFS
  hosts: namenode, datanode
  become: true
  roles:
    - install-hadoop-hdfs
  tags:
    - install_hadoop_hdfs
    - hdfs_namenode
    - hdfs_datanode

- name: Start Hadoop HDFS NameNode
  hosts: namenode
  roles:
    - namenode
  tags:
    - start_hdfs_namenode
    - start_component
    - hdfs_namenode

- name: Start Hadoop HDFS DataNodes
  hosts: datanode
  roles:
    - datanode
  tags:
    - start_hdfs_datanode
    - start_component
    - hdfs_datanode