apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config
      mountPath: "/config/config.conf"
      subPath: "config.conf"
  volumes:
  # You set volumes at the Pod level, then mount them into containers inside that Pod
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: test-config
